sudo: false

cache:
  directories:
    - $HOME/.stack

before_install:
- mkdir -p ~/.local/bin
- export PATH=$HOME/.local/bin:$PATH
- travis_retry curl -L https://www.stackage.org/stack/linux-x86_64 | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

script:
- stack --no-terminal setup
- stack --no-terminal install hscolour
- stack --no-terminal haddock
- mkdir site
- sed -r 's/\\\\\\\\(begin|end)\{code\}//' .stack-work/install/x86_64-linux/lts-5.8/7.10.3/doc/aligned-0.1.0.0/src/Aligned.html > site/index.html
- cp .stack-work/install/x86_64-linux/lts-5.8/7.10.3/doc/aligned-0.1.0.0/src/hscolour.css site/
- cd site
- git init
- git add .
- git config user.name "Travis CI"
- git config user.email "<>"
- git commit --message "Deploy to GitHub Pages"
- GITHUB_URL=https://$GITHUB_TOKEN@github.com/chris-martin/haskell-aligned.git
- # Redirect any output to /dev/null to avoid exposing the GitHub access token.
- git push --force --quiet $GITHUB_URL HEAD:gh-pages > /dev/null 2>&1

addons:
  apt:
    packages:
    - libgmp-dev

notifications:
  email: false
